# -*- coding: utf-8 -*-
"""thomson_scattering_params.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YUOhUWlT0Bl_GpmCtZ0CGps9oT2Aiq81
"""

from math import radians
from units import AU_TO_METERS
SIGMA_E = 7.95E-30 # Differential cross section for perpendicular scattering in m²·sr⁻¹.
WAVELENGTH = 5000E-10 # Target wavelength (5000A) in m.
T_SOL = 5778 # Solar temperature in K.
X = 1 * AU_TO_METERS # Distance between the Observer (Earth) and the Sun: O-S.
EPSILON = (radians(10)) # Elongation in rad.