# -*- coding: utf-8 -*-
"""universal_constants.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10OLAA64vl-oimonGMAjDmU4F0ohRSvdn
"""

h = 6.62607015E-34 # Planck's constant in J·s
c = 3E8 # m/s 
k = 1.38E-23 # Boltzmann's constant in J/K